### ISSUE TITLE
Problem: Dashboard cannot do true pagination of all available data

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#478]
The graphql API does not support pagination

**Comment by n1tranquilla** [comment]
This issue is blocked on the indexer supporting pagination https://github.com/Granola-Team/mina-indexer/issues/783

**Comment by robinbb** [comment]
Closing because even if the back-end supported pagination, there are numerous queries where merely paginating the data does not suffice to provide a usable way to interact with the data. (Example: paging through 9000 pages of data items - for what reason?) Instead, we will provide ways to search, sort, and filter the data.
