### ISSUE TITLE
Command Spotlight: Show which other blocks the transaction was found in

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#785]
By default, we show the canonical, but we might also want to see which other blocks (non-canonical) the transaction was also found in.

**Comment by trevorbernard** [comment]
There are 3 inputs that potentially can contribute on that page: `canonicity`, `state_hash`, and `txn_hash`. Since we populate the table with either canonical or non-canonical blocks. IMHO, it makes sense to to drill in by including the `state_hash` and `txn_hash`. There will be no ambiguity on the results since it will always return the correct result.

**Comment by trevorbernard** [comment]
This relates to this issue on the indexer: https://github.com/Granola-Team/mina-indexer/issues/1092#issuecomment-2161028157

**Comment by robinbb** [comment]
Moving milestone because that other issue is in another milestone.

**Comment by n1tranquilla** [comment]
This issue is meant to capture a new feature that we haven't developed yet, that would show other state hashes (non canonical blocks) that txn hash was found in. Moving this back to maintenance.
